<%@ Page Title="" Language="C#" MasterPageFile="~/Site1.Master" AutoEventWireup="true" CodeBehind="ManagerSettings.aspx.cs" Inherits="RopeyDVD.MangerSettings" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">

    <style>
         .defineborder{
            width:fit-content;
            border: 3px solid black;
            border-radius:1rem;
            margin: 40px auto 40px auto;
         }

         .tbW{
            width:200px;
            height:20px;
            border-radius:1rem;
            margin:auto;
            text-align:center;
            }

        .btnA{
            width:200px;
            height:40px;
            border-radius:1rem;
            text-align:center;
        }
   
    </style>

    <div class="defineborder">
    <h1  style="text-align:center">Assistant Details:</h1>
        <br />
        <%--<asp:GridView ID="GridViewDVD" runat="server" BackColor="White" BorderColor="#999999" BorderStyle="Solid" BorderWidth="1px" CellPadding="3" ForeColor="Black" GridLines="Vertical" Height="16px" HorizontalAlign="Center" Width="932px" AutoGenerateColumns="False"--%>
        <asp:GridView ID="GridViewAllUsers" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" 
            DataKeyNames="UserNumber" DataSourceID="SqlDataSourceAllUsers">
            <Columns>
                <asp:BoundField DataField="UserNumber" HeaderText="UserNumber" ReadOnly="True" SortExpression="UserNumber" />
                <asp:BoundField DataField="UserName" HeaderText="UserName" SortExpression="UserName" />
                <asp:BoundField DataField="UserType" HeaderText="UserType" SortExpression="UserType" />
                <asp:BoundField DataField="UserPassword" HeaderText="UserPassword" SortExpression="UserPassword" />
            </Columns>
            <%--Styling gridview--%>
                <FooterStyle BackColor="#24405c" ForeColor="white" />
                <HeaderStyle
                    BackColor="#24405c"
                    Font-Bold="True"
                    ForeColor="White"
                />
                <PagerStyle
                    BackColor="#24405c"
                    ForeColor="White"
                    HorizontalAlign="Center"
                />
                <RowStyle BackColor="White" ForeColor="#333333" />
        </asp:GridView>
        </div>
        <div class="borderdefine">
             
        <h1 style="font-size:30px; font-weight:300; text-align:center"> Add User</h1>
        <p style="font-size:20px; font-weight:300; text-align:center"> 
            <asp:TextBox ID="userNumberTextBox" runat="server" CssClass="tbW" placeholder="User Number" ></asp:TextBox>
            <asp:TextBox ID="userNameTextBox" runat="server" CssClass="tbW" placeholder="User Name" ></asp:TextBox>
        </p>

            <p style="font-size:20px; font-weight:300; text-align:center"> 
                <asp:DropDownList ID="DropDownListUserType" runat="server" class="tbW">
                    <asp:ListItem>Manager</asp:ListItem>
                    <asp:ListItem>Assistant</asp:ListItem>
                </asp:DropDownList>
            </p>
            <p style="font-size:20px; font-weight:300; text-align:center" id="userPasswordtextBox"> 
        
        <asp:TextBox ID="passwordTextBox" runat="server" CssClass="tbW" placeholder="password" TextMode="Password" ></asp:TextBox>


            </p>
            <p style="font-size:20px; font-weight:300; text-align:center"> 
            <asp:Button ID="bntAddUser" runat="server" Text="Add User" CssClass="btnA" Width="226px" BackColor="#1877F2" OnClick="bntAddUser_Click" Font-Bold="True" ForeColor="White" />
            </p>
            <p style="font-size:20px; font-weight:300; text-align:center"> 
            <asp:Label ID="successfulLabel" runat="server" style="color:red"></asp:Label>
        </p>

            <asp:SqlDataSource ID="SqlDataSourceAllUsers" runat="server" ConflictDetection="CompareAllValues" 
                ConnectionString="<%$ ConnectionStrings:RopeyDatabaseConnectionString %>" 
                DeleteCommand="DELETE FROM [User] WHERE [UserNumber] = @original_UserNumber AND [UserName] = @original_UserName AND [UserType] = @original_UserType AND [UserPassword] = @original_UserPassword" 
                InsertCommand="INSERT INTO [User] ([UserNumber], [UserName], [UserType], [UserPassword]) VALUES (@UserNumber, @UserName, @UserType, @UserPassword)" 
                OldValuesParameterFormatString="original_{0}"
                SelectCommand="SELECT * FROM [User]" 
                UpdateCommand="UPDATE [User] SET [UserName] = @UserName, [UserType] = @UserType, [UserPassword] = @UserPassword WHERE [UserNumber] = @original_UserNumber AND [UserName] = @original_UserName AND [UserType] = @original_UserType AND [UserPassword] = @original_UserPassword">
                <DeleteParameters>
                    <asp:Parameter Name="original_UserNumber" Type="String" />
                    <asp:Parameter Name="original_UserName" Type="String" />
                    <asp:Parameter Name="original_UserType" Type="String" />
                    <asp:Parameter Name="original_UserPassword" Type="String" />
                </DeleteParameters>
                <InsertParameters>
                    <asp:Parameter Name="original_UserNumber" Type="String" />
                    <asp:Parameter Name="original_UserName" Type="String" />
                    <asp:Parameter Name="original_UserType" Type="String" />
                    <asp:Parameter Name="original_UserPassword" Type="String" />
                </InsertParameters>
                <UpdateParameters>
                    <asp:Parameter Name="UserName" Type="String" />
                    <asp:Parameter Name="UserType" Type="String" />
                    <asp:Parameter Name="UserPassword" Type="String" />
                    <asp:Parameter Name="original_UserNumber" Type="String" />
                    <asp:Parameter Name="original_UserName" Type="String" />
                    <asp:Parameter Name="original_UserType" Type="String" />
                    <asp:Parameter Name="original_UserPassword" Type="String" />
                </UpdateParameters>
            </asp:SqlDataSource>
    <br />
    <br />
</div>
</asp:Content>
